linters:
  ImportantRule:
    enabled: false

  Indentation:
    width: 4

  NestingDepth:
    max_depth: 5

  PlaceholderInExtend:
    enabled: false

  PropertyUnits:
    properties:
      line-height: [] # No units allowed

  QualifyingElement:
    enabled: false

  SelectorDepth:
    max_depth: 5

  SelectorFormat:
    convention: hyphenated_BEM

  SpaceAfterPropertyColon:
    style: at_least_one_space
