# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
source:              ./app
title:               Deep-Fried Mind
tagline:             '– The blog'
description:         'Hey there. I''m a web developer (mainly front-end) and this is where I write about such topics – except for when I stray completely and write about other nonsense.'
url:                 http://blog.deepfriedmind.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Andreas Wahlqvist
  url:               https://twitter.com/deepfriedmind
  email:             andreas@deepfriedmind.com

# Custom vars
version:             1.0.0
