# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Files/folders to exclude from '_site' directory on build
exclude:
  - 'node_modules'
  - 'CNAME'
  - '*.sublime-project'
  - '*.sublime-workspace'
  - 'gulpfile.babel.js'
  - 'package.json'
  - 'LICENSE.md'
  - 'README.md'

# Setup
title:               Deep-Fried Mind
tagline:             'The blog'
description:         'Hey there. <br>My name is Andreas Wahlqvist and I''m a web developer (mainly of the front-end variety) as well as a general tech enthusiast. This is where I write about such topics <small><em>(except for when I stray completely and rant about other nonsense)</em></small>.'
url:                 http://blog.deepfriedmind.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Andreas Wahlqvist
  url:               http://deepfriedmind.com
  twitter:           deepfriedmind
  email:             andreas@deepfriedmind.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/deepfriedmind/deepfriedmind.github.io

# Disqus
disqus:
  shortname:         deepfriedmind

# Plugins
gems:
  - jekyll-sitemap
  - jemoji
